# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/jtag_dbg_block/jtag_dbg_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_dbg_block || ORIG_REF_NAME==jtag_dbg_block}]

# IP: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/jtag_dbg_block_jtag_axi_debugger_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_dbg_block_jtag_axi_debugger_ip_0_0 || ORIG_REF_NAME==jtag_dbg_block_jtag_axi_debugger_ip_0_0}]

# IP: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_1024MM_32STR/axi_datamover_1024MM_32STR.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_datamover_1024MM_32STR || ORIG_REF_NAME==axi_datamover_1024MM_32STR}]

# IP: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_128MM_32STR/axi_datamover_128MM_32STR.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_datamover_128MM_32STR || ORIG_REF_NAME==axi_datamover_128MM_32STR}]

# IP: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_256MM_32STR/axi_datamover_256MM_32STR.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_datamover_256MM_32STR || ORIG_REF_NAME==axi_datamover_256MM_32STR}]

# IP: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_32MM_32STR/axi_datamover_32MM_32STR.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_datamover_32MM_32STR || ORIG_REF_NAME==axi_datamover_32MM_32STR}]

# IP: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_512MM_32STR/axi_datamover_512MM_32STR.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_datamover_512MM_32STR || ORIG_REF_NAME==axi_datamover_512MM_32STR}]

# IP: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_64MM_32STR/axi_datamover_64MM_32STR.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_datamover_64MM_32STR || ORIG_REF_NAME==axi_datamover_64MM_32STR}]

# IP: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_mm32_to_axi_lite32/axi_mm32_to_axi_lite32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_mm32_to_axi_lite32 || ORIG_REF_NAME==axi_mm32_to_axi_lite32}]

# IP: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_mm64_to_axi_lite64/axi_mm64_to_axi_lite64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_mm64_to_axi_lite64 || ORIG_REF_NAME==axi_mm64_to_axi_lite64}]

# IP: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/vio_axi_jtag_dbg/vio_axi_jtag_dbg.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vio_axi_jtag_dbg || ORIG_REF_NAME==vio_axi_jtag_dbg}]

# IP: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/jtag_axi_debug_fifo_x64/jtag_axi_debug_fifo_x64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_axi_debug_fifo_x64 || ORIG_REF_NAME==jtag_axi_debug_fifo_x64}]

# IP: bd/jtag_dbg_block/ip/jtag_dbg_block_mig_7series_0_0/jtag_dbg_block_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_dbg_block_mig_7series_0_0 || ORIG_REF_NAME==jtag_dbg_block_mig_7series_0_0}]

# IP: bd/jtag_dbg_block/ip/jtag_dbg_block_axi_mem_intercon_0/jtag_dbg_block_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_dbg_block_axi_mem_intercon_0 || ORIG_REF_NAME==jtag_dbg_block_axi_mem_intercon_0}]

# IP: bd/jtag_dbg_block/ip/jtag_dbg_block_proc_sys_reset_0/jtag_dbg_block_proc_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_dbg_block_proc_sys_reset_0 || ORIG_REF_NAME==jtag_dbg_block_proc_sys_reset_0}]

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_1024MM_32STR/axi_datamover_1024MM_32STR_ooc.xdc

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_1024MM_32STR/axi_datamover_1024MM_32STR.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_datamover_1024MM_32STR || ORIG_REF_NAME==axi_datamover_1024MM_32STR}] {/U0 }]/U0 ]]

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_1024MM_32STR/axi_datamover_1024MM_32STR_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_datamover_1024MM_32STR || ORIG_REF_NAME==axi_datamover_1024MM_32STR}] {/U0 }]/U0 ]]

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_128MM_32STR/axi_datamover_128MM_32STR_ooc.xdc

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_128MM_32STR/axi_datamover_128MM_32STR.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_datamover_128MM_32STR || ORIG_REF_NAME==axi_datamover_128MM_32STR}] {/U0 }]/U0 ]]

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_128MM_32STR/axi_datamover_128MM_32STR_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_datamover_128MM_32STR || ORIG_REF_NAME==axi_datamover_128MM_32STR}] {/U0 }]/U0 ]]

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_256MM_32STR/axi_datamover_256MM_32STR_ooc.xdc

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_256MM_32STR/axi_datamover_256MM_32STR.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_datamover_256MM_32STR || ORIG_REF_NAME==axi_datamover_256MM_32STR}] {/U0 }]/U0 ]]

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_256MM_32STR/axi_datamover_256MM_32STR_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_datamover_256MM_32STR || ORIG_REF_NAME==axi_datamover_256MM_32STR}] {/U0 }]/U0 ]]

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_32MM_32STR/axi_datamover_32MM_32STR_ooc.xdc

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_32MM_32STR/axi_datamover_32MM_32STR.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_datamover_32MM_32STR || ORIG_REF_NAME==axi_datamover_32MM_32STR}] {/U0 }]/U0 ]]

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_32MM_32STR/axi_datamover_32MM_32STR_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_datamover_32MM_32STR || ORIG_REF_NAME==axi_datamover_32MM_32STR}] {/U0 }]/U0 ]]

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_512MM_32STR/axi_datamover_512MM_32STR_ooc.xdc

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_512MM_32STR/axi_datamover_512MM_32STR.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_datamover_512MM_32STR || ORIG_REF_NAME==axi_datamover_512MM_32STR}] {/U0 }]/U0 ]]

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_512MM_32STR/axi_datamover_512MM_32STR_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_datamover_512MM_32STR || ORIG_REF_NAME==axi_datamover_512MM_32STR}] {/U0 }]/U0 ]]

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_64MM_32STR/axi_datamover_64MM_32STR_ooc.xdc

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_64MM_32STR/axi_datamover_64MM_32STR.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_datamover_64MM_32STR || ORIG_REF_NAME==axi_datamover_64MM_32STR}] {/U0 }]/U0 ]]

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_datamover_64MM_32STR/axi_datamover_64MM_32STR_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_datamover_64MM_32STR || ORIG_REF_NAME==axi_datamover_64MM_32STR}] {/U0 }]/U0 ]]

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_mm32_to_axi_lite32/axi_mm32_to_axi_lite32_ooc.xdc

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/axi_mm64_to_axi_lite64/axi_mm64_to_axi_lite64_ooc.xdc

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/vio_axi_jtag_dbg/vio_axi_jtag_dbg_ooc.xdc

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/vio_axi_jtag_dbg/vio_axi_jtag_dbg.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vio_axi_jtag_dbg || ORIG_REF_NAME==vio_axi_jtag_dbg}] {/inst }]/inst ]]

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/jtag_axi_debug_fifo_x64/jtag_axi_debug_fifo_x64/jtag_axi_debug_fifo_x64.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jtag_axi_debug_fifo_x64 || ORIG_REF_NAME==jtag_axi_debug_fifo_x64}] {/U0 }]/U0 ]]

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_jtag_axi_debugger_ip_0_0/work/jtag_axi_debugger_ip/jtag_axi_debugger_ip.srcs/sources_1/ip/jtag_axi_debug_fifo_x64/jtag_axi_debug_fifo_x64_ooc.xdc

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_mig_7series_0_0/jtag_dbg_block_mig_7series_0_0/user_design/constraints/jtag_dbg_block_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_dbg_block_mig_7series_0_0 || ORIG_REF_NAME==jtag_dbg_block_mig_7series_0_0}]

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_mig_7series_0_0/jtag_dbg_block_mig_7series_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jtag_dbg_block_mig_7series_0_0 || ORIG_REF_NAME==jtag_dbg_block_mig_7series_0_0}]

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_proc_sys_reset_0/jtag_dbg_block_proc_sys_reset_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jtag_dbg_block_proc_sys_reset_0 || ORIG_REF_NAME==jtag_dbg_block_proc_sys_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_proc_sys_reset_0/jtag_dbg_block_proc_sys_reset_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jtag_dbg_block_proc_sys_reset_0 || ORIG_REF_NAME==jtag_dbg_block_proc_sys_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/jtag_dbg_block/ip/jtag_dbg_block_proc_sys_reset_0/jtag_dbg_block_proc_sys_reset_0_ooc.xdc

# XDC: bd/jtag_dbg_block/jtag_dbg_block_ooc.xdc
